routes/web.php
<?php

use App\Http\Controllers\LivreController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/login', function () {
    return view('auths.login');
})->name("auths.login");
Route::resource("livres",LivreController::class)->middleware("authMiddleware");

app/Models/Categorie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Categorie extends Model
{
    use HasFactory;
    protected $fillable=["nom","description"];

    public function livres(){
        return $this->hasMany(livre::class);
    }
}

app/Models/Livre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Livre extends Model
{
    use HasFactory;
    protected $fillable=["titre","pages","description","image"];

    public function categorie(){
        return $this->belongsTo(Categorie::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/LivreController.php
<?php

namespace App\Http\Controllers;

use App\Models\Livre;
use Illuminate\Http\Request;

class LivreController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $livresBuilder=Livre::query();
        $livres=$livresBuilder->paginate(20);
        return view("livres.index",compact("livres"));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view("livres.create");
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validateData=$request->validate([
            "titre"=>"required|max:255",
            "pages"=>"required|number",
            "description"=>"required",
            "categorie_id"=>"required",
        ]);
        if ($request->hasFile("image")) {
            $imagePath = $request->file("image")->store("livres/images", "public");
            $validateData["image"] = $imagePath;
        }
        Livre::create($validateData);
        return redirect()->route("livres.index");
    }

    /**
     * Display the specified resource.
     */
    public function show(Livre $livre)
    {
        return view("livres.show",compact("livre"));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Livre $livre)
    {
        return view("livres.edit",compact("livre"));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $validateData=$request->validate([
            "titre"=>"required|max:255",
            "pages"=>"required|number",
            "description"=>"required",
            "categorie_id"=>"required",
        ]);
        if ($request->hasFile("image")) {
            $imagePath = $request->file("image")->store("livres/images", "public");
            $validateData["image"] = $imagePath;
        }
        $livre = Livre::find($id);
        $livre->update($validateData);
        return redirect()->route("livres.index");
        
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Livre::destroy($id);
        return redirect()->route("livres.index");
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
</head>
<body>
    <nav>
        <ul>
            <li ><a href="{{route("livres.index")}}"></a>GestionLivres</li>
            <li ><a href="{{route("categories.index")}}"></a>Gestion Categorie</li>
        </ul>
    </nav>
    @yield('content')
    
</body>
</html>

resources/views/livres/index.blade.php
@extends('layouts.app')
@section('titre', 'Livres')
@section('content')
    <button class="btn btn-primary"><a href={{ route('livres.create') }}>Ajouter un livre</a> </button>
    <div class="table-responsive">
        <table class="table table-primary">
            <thead>
                <tr>
                    <th scope="col">Image</th>
                    <th scope="col">Titre</th>
                    <th scope="col">Categorie</th>
                    <th scope="col">Pages</th>
                    <th scope="col">Description</th>
                    <th scope="col" colspan="2">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($livres as $livre)
                    <tr class="">
                        <td scope="row"><img src="{{ asset('storage' . $livre->image) }}" alt=""> </td>
                        <td scope="row">{{ $livre->titre }}</td>
                        <td scope="row">{{ $livre->categorie->nom }}</td>
                        <td>{{ $livre->pages }}</td>
                        <td>{{ $livre->description }}</td>
                        <td>
                            <button><a href="{{ route('livres.edit', ['livre' => $livre->id]) }}">Modifier</a></button>
                        </td>
                        <td>
                            <form action="{{ route('livres.destroy', ['livre' => $livre->id]) }}" method="POST">
                                @csrf
                                @method('delete')
                                <input type="submit" value="Supprimer">
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection